### ISSUE TITLE
Build of nodejs-mongo-persistent fails, no idea how to fix it

### ISSUE THREAD

**Issue by dneary** [openshift/nodejs-ex#147]
I am following https://github.com/openshift/nodejs-ex/blob/master/README.md as indicated in the "Getting started" guide - and I have hit an issue where a build is failing, I think I can see what the issue is (clearly I made a mistake somewhere), but I have no idea how to fix it.

I cloned the repo to dneary/nodejs-ex, and when I try to build nodejs-mongo-persistent, the build fails with the following error: 

`Status

Status:
    Failed to fetch the input source. 
Started:
    5 hours ago – Nov 6, 2017 11:52:04 AM 
Duration:
    2 minutes, 39 seconds 
Triggered By:
    Manual build

Configuration created from nodejs-mongo-persistent

Build Strategy:
    Source
Builder Image:
    registry.access.redhat.com/rhscl/nodejs-6-rhel7@sha256:0860a4ccdc062f5ab05ec872298557f02f79c94b75820ded9a16211d8ab390ce
Source Type:
    Git
Source Repo:
    https://github.com/dnearynodejs-ex.git
Output Image:
    dneary-example/nodejs-mongo-persistent:latest 
Push Secret:
    builder-dockercfg-723t4
`
Notice the "Source repo" setting, missing a / between dneary and nodejs-ex.git - this is clearly the issue, probably introduced by not putting a trailing slash spomewhere it was needed in the getting started with OpenShift v3 docs, but now I don't know where this is set or how to fix it.

It would be nice to have "common issues" or a "guide to an OpenShift v3 app" which helps me identify and wipe/restart or identify and fix config issues like this in the Getting Started docs.

Thanks!

**Comment by dneary** [comment]
Actions->Edit configuration

**Comment by bparees** [comment]
you can use the web console to edit your buildconfig, or run "oc edit bc yourbuildconfigname" and fix the git repo reference.

if you want a clean start you can always just delete your project and create a new one.

**Comment by dneary** [comment]
Thanks Ben! "oc edit" has a lot in it, had not tried it. Can I delete an application with "oc delete" or does this only work with pods and services?

**Comment by bparees** [comment]
oc delete works for any resource, and you can delete most of the application resources with "oc delete all -l app=foo" to delete all resources with the label "app" equal to "foo" (depending how you created your resources, they will likely have an app label with some value) but there are some resources that are not covered by "all" (e.g. secrets).  For those you have to manually delete them (oc delete secret foobar).

So that's why if you don't care about the project, it's easiest to just delete the whole project.

(if you want to see what the delete is going to delete, you can run "oc get all -l app=foo")
